### ISSUE TITLE
Export issue in Node.js

### ISSUE THREAD

**Issue by dtsellos03** [cesine/ngram-natural-language-generator#3]
Due to the export statement ``` exports.generator = generator ``` in index.js, 

the following code in Node returns a ``` TypeError: generator is not a function ```

```
var generator = require('ngram-natural-language-generator');

generator({
	.......
	.......
});
```

Calling the generator function via ```generator.generator({ .... }); ``` works properly.

Potential solutions:

Changing the export statement in index.js to ```module.exports = generator``` makes the examples in the README.md work properly, but will break browser usage. 
The export statement could be changed to account for either node or browser usage and export accordingly (as addressed in https://stackoverflow.com/questions/12571737/module-exports-client-side ). Or the examples in the README could be changed to use ```generator.generator({...})```. 

I would happy to work on any of those if help is wanted.

Thanks for making such a useful module!

**Comment by cesine** [comment]
thanks for raising this! for now i'll just update the Readme 

i'll look into using this but first i'll add some browser tests

```
if (typeof exports !== 'undefined') {
  if (typeof module !== 'undefined' && module.exports) {
    exports = module.exports = NLG;
  }
  exports.NLG = NLG;
} else {
  root['NLG'] = NLG;
}
```
